install_requirements:
	pip3 install git+https://github.com/Accelergy-Project/accelergy.git git+https://github.com/Accelergy-Project/timeloopfe.git
	pip3 install -r requirements.txt

jupyter:
	jupyter lab --ip=`hostname` --no-browser
